[package]
name = "federation-integration-tests"
description = "Integration tests for datafusion-federation"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
publish = false

[dependencies]
anyhow = "1.0.98"
duckdb = "1.1.3"
datafusion-table-providers = { git = "https://github.com/datafusion-contrib/datafusion-table-providers.git", rev = "11e6ee6ce966bed75bfdf75204193503f1593cef", features = ["duckdb", "duckdb-federation"] } # phillip/250527-federation-upgrade
datafusion = { workspace = true }
tokio = { version = "1.35", features = ["rt", "rt-multi-thread", "macros"] }
async-trait.workspace = true
tonic = "0.12.2"
futures.workspace = true
insta = { version = "1.42.0", features = ["filters"]}
chrono = "0.4.31"
datafusion-federation.workspace = true